apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nextech-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: abhishek@saxecap.com
    privateKeySecretRef:
      name: nextech-letsencrypt-prod-private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
