apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitemap-processor
  namespace: nextech
spec:
  selector:
    matchLabels:
      app: sitemap-processor
  template:
    metadata:
      labels:
        app: sitemap-processor
    spec:
      containers:
        - name: sitemap-processor
          image: 590184135143.dkr.ecr.us-east-1.amazonaws.com/nextech-sitemap-processor:v1.2
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: appconfig
                  key: ENV
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_DB_HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_DATABASE_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_DB_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_RABBITMQ_URL
            - name: INPUT_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: appconfig
                  key: SITEMAP_PROCESSOR_INPUT_QUEUE_NAME
            - name: OUTPUT_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: appconfig
                  key: ASSET_PROCESSOR_INPUT_QUEUE_NAME
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: appconfig
                  key: SENTRY_DSN
            - name: SMARTPROXY_AUTH
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_SMARTPROXY_AUTH
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: esosecret
                  key: NEXTECH_OPENAI_API_KEY
