"""bot deployed_at column

Revision ID: 7c0e1ba5d2ab
Revises: ce279678260c
Create Date: 2024-05-25 15:33:43.281712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0e1ba5d2ab'
down_revision = 'ce279678260c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('bot_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_assets', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.drop_column('deployed_at')

    # ### end Alembic commands ###
