"""add cfg_type on message

Revision ID: c90457ebbab7
Revises: 21e83fd475da
Create Date: 2024-06-17 14:53:51.076662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90457ebbab7'
down_revision = '21e83fd475da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cfg_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('cfg_type')

    # ### end Alembic commands ###
