"""remove unique constraint on client name

Revision ID: d75673328580
Revises: c90457ebbab7
Create Date: 2024-06-28 15:03:02.356373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75673328580'
down_revision = 'c90457ebbab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('client_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_unique_constraint('client_name_key', ['name'])

    # ### end Alembic commands ###
