"""rm uniqueness of bot names

Revision ID: d7b1cfcc04f2
Revises: 7c0e1ba5d2ab
Create Date: 2024-05-26 09:16:41.737258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b1cfcc04f2'
down_revision = '7c0e1ba5d2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.drop_constraint('bot_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.create_unique_constraint('bot_name_key', ['name'])

    # ### end Alembic commands ###
